/**
 * Generated by scripts/generate-sdks.mjs.
 * Do not edit this file manually.
 */

export const endpointManifest = {
  "availability": {
    "bulkCheckDomains": {
      "operationId": "bulkCheckDomains",
      "title": "Bulk Domain Check",
      "description": "Check availability of multiple complete domain names at once.",
      "method": "POST",
      "path": "/v1/status/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "checkDomainAvailability": {
      "operationId": "checkDomainAvailability",
      "title": "Domain Availability",
      "description": "Check if a domain name is available for registration across multiple TLDs. Uses RDAP for authoritative results. Primary format: name + tlds. Single-domain shortcut: domain=example.com.",
      "method": "GET",
      "path": "/v1/status",
      "pathParams": [],
      "queryParams": [
        "name",
        "tlds",
        "domain",
        "prefer_cache"
      ],
      "hasBody": false
    },
    "createDomainDiscoveryJob": {
      "operationId": "createDomainDiscoveryJob",
      "title": "Create Domain Discovery Job",
      "description": "Create a resumable asynchronous search over a curated English single-word corpus sourced from iannuttall/unclaimed under the MIT License. Check each selected word across 1 to 5 supported TLDs, with a hard limit of 100 word-TLD checks per job. Available, registered, and unknown remain distinct outcomes. Jobs use the existing batch status, results, and cancellation lifecycle.",
      "method": "POST",
      "path": "/v1/domain-discovery/jobs",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "getCoverage": {
      "operationId": "getCoverage",
      "title": "RDAP Coverage",
      "description": "Get information about which TLDs are supported and their RDAP server status.",
      "method": "GET",
      "path": "/v1/coverage",
      "pathParams": [],
      "queryParams": [
        "live"
      ],
      "hasBody": false
    }
  },
  "dns": {
    "buildDmarc": {
      "operationId": "buildDmarc",
      "title": "DMARC Builder",
      "description": "Build a DMARC record with policy, reporting, and alignment options.",
      "method": "POST",
      "path": "/v1/tools/dmarc/build",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "buildSpf": {
      "operationId": "buildSpf",
      "title": "SPF Builder",
      "description": "Build an SPF record from configuration options with validation and recommendations.",
      "method": "POST",
      "path": "/v1/tools/spf/build",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "bulkDnsPropagation": {
      "operationId": "bulkDnsPropagation",
      "title": "Bulk DNS Resolver Comparison",
      "description": "Compare answers from the configured public recursive DNS resolvers for up to 10 domains. Results preserve input order and report per-domain errors.",
      "method": "POST",
      "path": "/v1/dns/propagation/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "checkDkim": {
      "operationId": "checkDkim",
      "title": "DKIM Check",
      "description": "Check a specific DKIM selector for a domain and validate the public key.",
      "method": "GET",
      "path": "/v1/tools/dkim/check",
      "pathParams": [],
      "queryParams": [
        "domain",
        "selector"
      ],
      "hasBody": false
    },
    "discoverDkim": {
      "operationId": "discoverDkim",
      "title": "DKIM Discovery",
      "description": "Discover DKIM selectors for a domain by checking common selector names.",
      "method": "GET",
      "path": "/v1/tools/dkim/discover",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "flattenSpf": {
      "operationId": "flattenSpf",
      "title": "SPF Flattener",
      "description": "Flatten SPF record by resolving all includes into IP addresses to reduce DNS lookups.",
      "method": "POST",
      "path": "/v1/tools/spf/flatten",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "getAllDnsRecords": {
      "operationId": "getAllDnsRecords",
      "title": "DNS All Records",
      "description": "Get all major DNS record types for a domain in a single call with IPv6 parity, TXT classification, wildcard probe, and warning signals.",
      "method": "GET",
      "path": "/v1/dns/all",
      "pathParams": [],
      "queryParams": [
        "domain",
        "wildcard_probe"
      ],
      "hasBody": false
    },
    "getDnsHistory": {
      "operationId": "getDnsHistory",
      "title": "DNS History",
      "description": "Review day-level DNS record values observed by successful DomScan DNS lookups. This lookup-driven observation log can miss changes between lookups and does not include external passive DNS sources.",
      "method": "GET",
      "path": "/v1/dns/history",
      "pathParams": [],
      "queryParams": [
        "domain",
        "type",
        "from",
        "to",
        "limit"
      ],
      "hasBody": false
    },
    "getDnsPropagation": {
      "operationId": "getDnsPropagation",
      "title": "DNS Resolver Comparison",
      "description": "Compare answers from DomScan's configured public recursive resolvers. Without expected, the percentage reports the largest resolver-convergence cohort. With expected, it reports providers whose answers match that value. This is not a geographic or worldwide propagation measurement.",
      "method": "GET",
      "path": "/v1/dns/propagation",
      "pathParams": [],
      "queryParams": [
        "domain",
        "type",
        "expected"
      ],
      "hasBody": false
    },
    "getDnsRecords": {
      "operationId": "getDnsRecords",
      "title": "DNS Lookup",
      "description": "Query A, AAAA, MX, NS, TXT, CAA and other DNS records programmatically with TXT classification and additive warning signals.",
      "method": "GET",
      "path": "/v1/dns",
      "pathParams": [],
      "queryParams": [
        "domain",
        "type"
      ],
      "hasBody": false
    },
    "getDnsSecurity": {
      "operationId": "getDnsSecurity",
      "title": "DNS Security",
      "description": "Analyze DNS security configuration including SPF, DKIM, DMARC, DNSSEC, CAA, MTA-STS, TLS-RPT, resolver latency, and AXFR exposure.",
      "method": "GET",
      "path": "/v1/dns/security",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getDnsServers": {
      "operationId": "getDnsServers",
      "title": "DNS Resolver Providers",
      "description": "List the public recursive DoH providers used for resolver comparison. These are global anycast services, not geographic probes.",
      "method": "GET",
      "path": "/v1/dns/servers",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "validateDmarc": {
      "operationId": "validateDmarc",
      "title": "DMARC Validator",
      "description": "Validate a DMARC record for syntax errors and configuration issues.",
      "method": "POST",
      "path": "/v1/tools/dmarc/validate",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "validateSpf": {
      "operationId": "validateSpf",
      "title": "SPF Validator",
      "description": "Validate an SPF record for syntax errors, DNS lookup limits, and best practices.",
      "method": "POST",
      "path": "/v1/tools/spf/validate",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    }
  },
  "domain": {
    "bulkDomainValue": {
      "operationId": "bulkDomainValue",
      "title": "Bulk Domain Valuation",
      "description": "Get value estimates for multiple domains at once.",
      "method": "POST",
      "path": "/v1/value/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "bulkGetDomainProfile": {
      "operationId": "bulkGetDomainProfile",
      "title": "Domain Profile",
      "description": "Get normalized RDAP registration data: registrar, dates, nameservers, DNSSEC status.",
      "method": "POST",
      "path": "/v1/profile/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "compareBrandNames": {
      "operationId": "compareBrandNames",
      "title": "Compare Brand Names",
      "description": "Compare up to 50 candidate brand names and return ranked scores.",
      "method": "POST",
      "path": "/v1/score/compare",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "compareDomains": {
      "operationId": "compareDomains",
      "title": "Domain Compare",
      "description": "Compare two domains side-by-side across multiple metrics and attributes.",
      "method": "GET",
      "path": "/v1/compare",
      "pathParams": [],
      "queryParams": [
        "domains"
      ],
      "hasBody": false
    },
    "getDomainHealth": {
      "operationId": "getDomainHealth",
      "title": "Domain Health",
      "description": "Comprehensive health checks with DNS, SSL, email, extended TLS and HTTP versions, HSTS audit, SMTP TLS, and MX FCrDNS signals.",
      "method": "GET",
      "path": "/v1/health",
      "pathParams": [],
      "queryParams": [
        "domain",
        "details"
      ],
      "hasBody": false
    },
    "getDomainOverview": {
      "operationId": "getDomainOverview",
      "title": "Domain Overview",
      "description": "Aggregate DNS, RDAP registration, health, reputation, and popularity observations in one response, with null unknowns and per-component freshness.",
      "method": "GET",
      "path": "/v1/overview",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getDomainPopularity": {
      "operationId": "getDomainPopularity",
      "title": "Domain Popularity",
      "description": "Get the current research-grade Tranco rank and bucket for a domain, with explicit ranked, unranked, and unknown states, source date, cache state, and optional lookup-driven history.",
      "method": "GET",
      "path": "/v1/popularity",
      "pathParams": [],
      "queryParams": [
        "domain",
        "include_history",
        "history_limit"
      ],
      "hasBody": false
    },
    "getDomainPopularityHistory": {
      "operationId": "getDomainPopularityHistory",
      "title": "Domain Popularity History",
      "description": "Read prior Tranco observations recorded by DomScan lookups. This is a lookup-driven history, not a complete daily rank series.",
      "method": "GET",
      "path": "/v1/popularity/history",
      "pathParams": [],
      "queryParams": [
        "domain",
        "limit"
      ],
      "hasBody": false
    },
    "getDomainProfile": {
      "operationId": "getDomainProfile",
      "title": "Domain Profile",
      "description": "Get normalized RDAP registration data: registrar, dates, nameservers, DNSSEC status.",
      "method": "GET",
      "path": "/v1/profile",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getDomainScore": {
      "operationId": "getDomainScore",
      "title": "Domain Score",
      "description": "Calculate an overall domain quality score based on multiple factors.",
      "method": "GET",
      "path": "/v1/score",
      "pathParams": [],
      "queryParams": [
        "name",
        "domain"
      ],
      "hasBody": false
    },
    "getDomainValue": {
      "operationId": "getDomainValue",
      "title": "Domain Valuation",
      "description": "Algorithmic domain value estimates based on length, TLD tier, dictionary words, and brandability.",
      "method": "GET",
      "path": "/v1/value",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getQuickHealth": {
      "operationId": "getQuickHealth",
      "title": "Quick Health Check",
      "description": "Fast health check with essential metrics only.",
      "method": "GET",
      "path": "/v1/health/quick",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getScoreInfo": {
      "operationId": "getScoreInfo",
      "title": "Brand Scoring Reference",
      "description": "Returns scoring dimensions, grade scale, and related scoring endpoints.",
      "method": "GET",
      "path": "/v1/score/info",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getTldDetail": {
      "operationId": "getTldDetail",
      "title": "TLD Detail",
      "description": "Get detailed information about a specific TLD.",
      "method": "GET",
      "path": "/v1/tlds/:tld",
      "pathParams": [
        "tld"
      ],
      "queryParams": [],
      "hasBody": false
    },
    "getTlds": {
      "operationId": "getTlds",
      "title": "TLD List",
      "description": "Get list of all supported TLDs with metadata.",
      "method": "GET",
      "path": "/v1/tlds",
      "pathParams": [],
      "queryParams": [
        "type",
        "trust_tier",
        "use_case"
      ],
      "hasBody": false
    },
    "suggestDomains": {
      "operationId": "suggestDomains",
      "title": "Domain Suggestions",
      "description": "AI-powered domain name generator. Get brandable, short, and keyword-rich suggestions based on your keywords.",
      "method": "GET",
      "path": "/v1/suggest",
      "pathParams": [],
      "queryParams": [
        "keywords",
        "tlds",
        "style",
        "industry",
        "language",
        "limit",
        "check"
      ],
      "hasBody": false
    }
  },
  "intelligence": {
    "bulkGetHosting": {
      "operationId": "bulkGetHosting",
      "title": "Bulk Hosting Detection",
      "description": "Detect hosting, CDN, WAF, DNS, and email infrastructure for up to 10 domains. Results preserve input order and include per-domain errors.",
      "method": "POST",
      "path": "/v1/hosting/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "bulkGetUrlIntelligence": {
      "operationId": "bulkGetUrlIntelligence",
      "title": "Bulk Unified URL Intelligence",
      "description": "Extract normalized URL intelligence for up to 10 public URLs. Results preserve input order and include per-item errors.",
      "method": "POST",
      "path": "/v1/url-intelligence/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "bulkGetWebsiteIdentityAssets": {
      "operationId": "bulkGetWebsiteIdentityAssets",
      "title": "Bulk Website Identity Assets",
      "description": "Extract website identity assets for up to 10 domains. Results preserve input order and include per-item errors.",
      "method": "POST",
      "path": "/v1/identity-assets/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "bulkResolveInternetIdentity": {
      "operationId": "bulkResolveInternetIdentity",
      "title": "Bulk Internet Identity Resolution",
      "description": "Resolve public identities for up to 10 company domains. Results preserve input order and include per-item errors.",
      "method": "POST",
      "path": "/v1/identity-resolution/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "cancelTechScanJob": {
      "operationId": "cancelTechScanJob",
      "title": "Cancel Async Tech Scan Job",
      "description": "Cancel unstarted technology scan work and settle item-level refunds. Work already in progress may finish and remains available in the job results.",
      "method": "DELETE",
      "path": "/v1/tech/jobs/:job_id",
      "pathParams": [
        "job_id"
      ],
      "queryParams": [],
      "hasBody": false
    },
    "categorizeWebsite": {
      "operationId": "categorizeWebsite",
      "title": "Website Categorization",
      "description": "Classify websites into DomScan IAB-inspired categories using multi-signal analysis: keywords, schema.org, Open Graph, TLD heuristics, URL patterns, and HTML structure.",
      "method": "GET",
      "path": "/v1/categorize",
      "pathParams": [],
      "queryParams": [
        "url",
        "domain",
        "skip_cache",
        "min_confidence"
      ],
      "hasBody": false
    },
    "categorizeWebsiteBulk": {
      "operationId": "categorizeWebsiteBulk",
      "title": "Bulk Website Categorization",
      "description": "Categorize up to 10 websites in parallel with caching.",
      "method": "POST",
      "path": "/v1/categorize/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "createScrapeJob": {
      "operationId": "createScrapeJob",
      "title": "Create Async Scrape Job",
      "description": "Queue 1 to 100 public page scrapes for asynchronous processing. Batch jobs are available to paid accounts, require an idempotency key, allow up to three active jobs and 300 queued items per account, and bill each accepted URL at the selected mode price. CAPTCHA solving and premium proxy selection are not offered.",
      "method": "POST",
      "path": "/v1/scrape/jobs",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "createTechScanJob": {
      "operationId": "createTechScanJob",
      "title": "Create Async Tech Scan Job",
      "description": "Create a durable asynchronous technology scan job for up to 100 public targets. Supports fast, JavaScript-rendered, and bounded same-origin deep modes with item-level billing and refunds.",
      "method": "POST",
      "path": "/v1/tech/jobs",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "getCategorizationTaxonomy": {
      "operationId": "getCategorizationTaxonomy",
      "title": "Categorization Taxonomy",
      "description": "List the DomScan IAB-inspired category IDs, response category names, taxonomy names, and subcategories returned by the Website Categorization API.",
      "method": "GET",
      "path": "/v1/categorize/taxonomy",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getCompany": {
      "operationId": "getCompany",
      "title": "Company Lookup",
      "description": "Extract source-backed organization names, descriptions, declared social links, MX-inferred email providers, confidence, and provenance from public website and DNS metadata. Enrichment-only fields can be null.",
      "method": "GET",
      "path": "/v1/company",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getDomainSimilarity": {
      "operationId": "getDomainSimilarity",
      "title": "Domain Similarity",
      "description": "Compare domains for similarity. Detect typosquatting with multiple algorithms.",
      "method": "GET",
      "path": "/v1/similarity",
      "pathParams": [],
      "queryParams": [
        "domain1",
        "domain2"
      ],
      "hasBody": false
    },
    "getHosting": {
      "operationId": "getHosting",
      "title": "Hosting Detection",
      "description": "Detect hosting provider, CDN, WAF, DNS provider, and email infrastructure.",
      "method": "GET",
      "path": "/v1/hosting",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getParkingDetection": {
      "operationId": "getParkingDetection",
      "title": "Parking Detection",
      "description": "Detect if a domain is parked or listed for sale on aftermarket platforms. Identifies parking providers via DNS, HTTP redirect, and HTML content analysis.",
      "method": "GET",
      "path": "/v1/parking",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getRedirects": {
      "operationId": "getRedirects",
      "title": "Redirect Chain",
      "description": "Follow URL redirect chains. Detect HTTPS upgrades, domain changes, and landing pages.",
      "method": "GET",
      "path": "/v1/redirects",
      "pathParams": [],
      "queryParams": [
        "url",
        "domain"
      ],
      "hasBody": false
    },
    "getScrapeJob": {
      "operationId": "getScrapeJob",
      "title": "Get Async Scrape Job",
      "description": "Get owner-scoped progress, item counts, billing settlement, and expiration details.",
      "method": "GET",
      "path": "/v1/scrape/jobs/:job_id",
      "pathParams": [
        "job_id"
      ],
      "queryParams": [],
      "hasBody": false
    },
    "getScrapeJobResults": {
      "operationId": "getScrapeJobResults",
      "title": "Get Async Scrape Results",
      "description": "Get ordered, paginated results for an owner-scoped scrape job. Full page results expire after 24 hours.",
      "method": "GET",
      "path": "/v1/scrape/jobs/:job_id/results",
      "pathParams": [
        "job_id"
      ],
      "queryParams": [
        "limit",
        "offset"
      ],
      "hasBody": false
    },
    "getTechScanJob": {
      "operationId": "getTechScanJob",
      "title": "Get Async Tech Scan Job",
      "description": "Get owner-scoped progress, item counts, billing settlement, and expiration details for a technology scan job.",
      "method": "GET",
      "path": "/v1/tech/jobs/:job_id",
      "pathParams": [
        "job_id"
      ],
      "queryParams": [],
      "hasBody": false
    },
    "getTechScanJobResults": {
      "operationId": "getTechScanJobResults",
      "title": "Get Async Tech Scan Results",
      "description": "Get ordered, signed-cursor-paginated results for a technology scan job. Full results expire after 48 hours and operational job records expire after seven days.",
      "method": "GET",
      "path": "/v1/tech/jobs/:job_id/results",
      "pathParams": [
        "job_id"
      ],
      "queryParams": [
        "cursor",
        "limit"
      ],
      "hasBody": false
    },
    "getTechStack": {
      "operationId": "getTechStack",
      "title": "Tech Stack Detection",
      "description": "Detect 500+ verified website technologies across 80+ categories using bounded HTTP signals, rendered JavaScript globals, observed network URLs, and same-origin multi-page analysis. Returns confidence, sanitized evidence scoped to each page, caveats, provenance, explicit limits, and complete or partial coverage.",
      "method": "GET",
      "path": "/v1/tech",
      "pathParams": [],
      "queryParams": [
        "url",
        "domain",
        "mode",
        "max_pages",
        "skip_cache"
      ],
      "hasBody": false
    },
    "getUrlIntelligence": {
      "operationId": "getUrlIntelligence",
      "title": "Unified URL Intelligence",
      "description": "Extract normalized metadata, link-preview assets, Open Graph and Twitter Card fields, canonical URL, robots directives, structured-data types, security headers, links, contacts, and declared profiles from a public URL.",
      "method": "GET",
      "path": "/v1/url-intelligence",
      "pathParams": [],
      "queryParams": [
        "url",
        "skip_cache"
      ],
      "hasBody": false
    },
    "getWebsiteIdentityAssets": {
      "operationId": "getWebsiteIdentityAssets",
      "title": "Website Identity Assets",
      "description": "Discover a website organization name, logo candidates, favicons, touch icons, preview image, theme color, manifest, and declared social profiles from public website metadata.",
      "method": "GET",
      "path": "/v1/identity-assets",
      "pathParams": [],
      "queryParams": [
        "domain",
        "skip_cache"
      ],
      "hasBody": false
    },
    "listTechScanJobs": {
      "operationId": "listTechScanJobs",
      "title": "List Async Tech Scan Jobs",
      "description": "List recent short-lived technology scan jobs for the authenticated account.",
      "method": "GET",
      "path": "/v1/tech/jobs",
      "pathParams": [],
      "queryParams": [
        "limit",
        "cursor"
      ],
      "hasBody": false
    },
    "postTechStackBulk": {
      "operationId": "postTechStackBulk",
      "title": "Bulk Tech Stack Detection",
      "description": "Run up to 10 ordered fast technology scans in one request. Each attempted target is billed independently, including target-site failures. Verified DomScan service failures are refunded independently.",
      "method": "POST",
      "path": "/v1/tech/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "resolveInternetIdentity": {
      "operationId": "resolveInternetIdentity",
      "title": "Internet Identity Resolution",
      "description": "Resolve a company domain into public social, developer, creator, federated, and app-store identities explicitly declared by its website.",
      "method": "GET",
      "path": "/v1/identity-resolution",
      "pathParams": [],
      "queryParams": [
        "domain",
        "skip_cache"
      ],
      "hasBody": false
    },
    "scrapePage": {
      "operationId": "scrapePage",
      "title": "Single Page Scrape",
      "description": "Retrieve one public web page with bounded redirects and response size. Standard requests use one attempt, resilient requests may use one eligible retry, and rendered modes execute page JavaScript in an isolated browser. Free accounts can use standard mode with lower request, concurrency, daily, monthly, and response-size limits. CAPTCHA solving and premium proxy selection are not offered. Target-site failures remain billable after processing starts; verified platform failures are refunded.",
      "method": "POST",
      "path": "/v1/scrape",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    }
  },
  "meta": {
    "cancelApiBatch": {
      "operationId": "cancelApiBatch",
      "title": "Cancel Async API Batch",
      "description": "Cancel unstarted batch items and refund their item charges. An item already being processed may finish.",
      "method": "DELETE",
      "path": "/v1/batches/:job_id",
      "pathParams": [
        "job_id"
      ],
      "queryParams": [],
      "hasBody": false
    },
    "createApiBatch": {
      "operationId": "createApiBatch",
      "title": "Create Async API Batch",
      "description": "Queue up to 100 supported GET API requests for asynchronous processing. Each item keeps normal endpoint pricing and refund rules. Target-site outcomes remain billed, while verified service failures are refunded independently.",
      "method": "POST",
      "path": "/v1/batches",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "downloadEmailBlacklist": {
      "operationId": "downloadEmailBlacklist",
      "title": "Download Disposable Email Dataset",
      "description": "Download the full disposable email domain dataset in various formats.",
      "method": "GET",
      "path": "/v1/email/blacklist/download",
      "pathParams": [],
      "queryParams": [
        "format"
      ],
      "hasBody": false
    },
    "getApiBatch": {
      "operationId": "getApiBatch",
      "title": "Get Async API Batch",
      "description": "Get progress, item counts, billing settlement, webhook delivery state, and expiration for an account API batch.",
      "method": "GET",
      "path": "/v1/batches/:job_id",
      "pathParams": [
        "job_id"
      ],
      "queryParams": [],
      "hasBody": false
    },
    "getApiBatchResults": {
      "operationId": "getApiBatchResults",
      "title": "Get Async API Batch Results",
      "description": "Get ordered JSON results or download all items as RFC 4180 CSV for an account API batch. Results and job metadata expire 24 hours after creation.",
      "method": "GET",
      "path": "/v1/batches/:job_id/results",
      "pathParams": [
        "job_id"
      ],
      "queryParams": [
        "after",
        "limit",
        "format"
      ],
      "hasBody": false
    },
    "getEmailBlacklistInfo": {
      "operationId": "getEmailBlacklistInfo",
      "title": "Disposable Email Dataset",
      "description": "Browse the disposable email domain dataset as a paginated data feed.",
      "method": "GET",
      "path": "/v1/email/blacklist",
      "pathParams": [],
      "queryParams": [
        "limit",
        "offset",
        "format"
      ],
      "hasBody": false
    },
    "getPricingInfo": {
      "operationId": "getPricingInfo",
      "title": "API Pricing Info",
      "description": "Get credit costs per endpoint and API pricing information.",
      "method": "GET",
      "path": "/v1/pricing",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "listApiBatches": {
      "operationId": "listApiBatches",
      "title": "List Async API Batches",
      "description": "List unexpired asynchronous API batches for the active customer account.",
      "method": "GET",
      "path": "/v1/batches",
      "pathParams": [],
      "queryParams": [
        "limit"
      ],
      "hasBody": false
    }
  },
  "osint": {
    "bulkGetRdap": {
      "operationId": "bulkGetRdap",
      "title": "Bulk RDAP Lookup",
      "description": "Query raw RDAP data for up to 10 domains, IP addresses, CIDR ranges, or autonomous system numbers. One query type applies to the whole batch.",
      "method": "POST",
      "path": "/v1/rdap/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "bulkWhois": {
      "operationId": "bulkWhois",
      "title": "Bulk WHOIS Lookup",
      "description": "Get WHOIS data for multiple domains at once.",
      "method": "POST",
      "path": "/v1/whois/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "getDomainLifecycle": {
      "operationId": "getDomainLifecycle",
      "title": "Domain Lifecycle",
      "description": "Get domain lifecycle information including registration date, expiration date, age, and lifecycle phase. Returns Fastly-style status flags.",
      "method": "GET",
      "path": "/v1/lifecycle",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getIpInfo": {
      "operationId": "getIpInfo",
      "title": "IP Geolocation",
      "description": "Get IP or resolved-domain geolocation and ASN data, provider security flags, coarse hosting classification, and FCrDNS. PTR-based signals are derived from the IP, never the caller hostname.",
      "method": "GET",
      "path": "/v1/ip",
      "pathParams": [],
      "queryParams": [
        "ip",
        "domain"
      ],
      "hasBody": false
    },
    "getMacInfo": {
      "operationId": "getMacInfo",
      "title": "MAC Address Lookup",
      "description": "Lookup MAC address vendor information. Identify network device manufacturers.",
      "method": "GET",
      "path": "/v1/mac",
      "pathParams": [],
      "queryParams": [
        "mac"
      ],
      "hasBody": false
    },
    "getMacLookupInfo": {
      "operationId": "getMacLookupInfo",
      "title": "MAC Lookup Reference",
      "description": "Returns parameter help and an example response for the MAC address lookup endpoint.",
      "method": "GET",
      "path": "/v1/mac/info",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getRdap": {
      "operationId": "getRdap",
      "title": "RDAP Lookup",
      "description": "Get raw RDAP response for a domain, IP address, or autonomous system number.",
      "method": "GET",
      "path": "/v1/rdap",
      "pathParams": [],
      "queryParams": [
        "query",
        "type",
        "domain"
      ],
      "hasBody": false
    },
    "getWhois": {
      "operationId": "getWhois",
      "title": "WHOIS Lookup",
      "description": "Get structured WHOIS/RDAP registration data for a domain.",
      "method": "GET",
      "path": "/v1/whois",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getWhoisHistory": {
      "operationId": "getWhoisHistory",
      "title": "WHOIS History",
      "description": "Query the DomScan WHOIS observation log. A qualifying fresh, successful RDAP-backed GET /v1/whois or /v2/whois lookup can record at most one normalized snapshot per domain per UTC day. Cached responses, bulk lookups, history reads, and traditional WHOIS-only fallbacks do not add snapshots. This is not a global historical WHOIS archive and does not provide registrant identity or contact history.",
      "method": "GET",
      "path": "/v1/whois/history",
      "pathParams": [],
      "queryParams": [
        "domain",
        "limit"
      ],
      "hasBody": false
    },
    "getWhoisV2": {
      "operationId": "getWhoisV2",
      "title": "Enhanced WHOIS Lookup",
      "description": "Fetch RDAP and traditional WHOIS in parallel, then merge available abuse contacts, registrar WHOIS details, glue addresses, and raw WHOIS evidence into the normalized response.",
      "method": "GET",
      "path": "/v2/whois",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    }
  },
  "pricing": {
    "bulkPricing": {
      "operationId": "bulkPricing",
      "title": "Bulk Pricing",
      "description": "Read daily standard-price rows for multiple TLDs. Each unique TLD and selected registrar pair costs one credit.",
      "method": "POST",
      "path": "/v1/prices/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "comparePrices": {
      "operationId": "comparePrices",
      "title": "Compare Registrar Prices",
      "description": "Compare daily standard-TLD rows and separate credential-backed exact-domain quotes without inferring missing operation prices.",
      "method": "GET",
      "path": "/v1/prices/compare",
      "pathParams": [],
      "queryParams": [
        "domain",
        "registrars",
        "skip_cache"
      ],
      "hasBody": false
    },
    "getPrices": {
      "operationId": "getPrices",
      "title": "Domain Pricing",
      "description": "Read daily standard-TLD price snapshots from verified official registrar sources. One credit is charged per unique TLD and selected registrar pair.",
      "method": "GET",
      "path": "/v1/prices",
      "pathParams": [],
      "queryParams": [
        "tlds",
        "registrars",
        "skip_cache"
      ],
      "hasBody": false
    },
    "getRegistrars": {
      "operationId": "getRegistrars",
      "title": "List Registrars",
      "description": "List registrar metadata and identify which registrars currently have integrated DomScan pricing sources.",
      "method": "GET",
      "path": "/v1/prices/registrars",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getTldPricing": {
      "operationId": "getTldPricing",
      "title": "TLD Pricing",
      "description": "Read daily standard-price rows for one TLD, with registrar filters, provenance, freshness, and pair-based billing.",
      "method": "GET",
      "path": "/v1/prices/tld/:tld",
      "pathParams": [
        "tld"
      ],
      "queryParams": [
        "registrars",
        "skip_cache"
      ],
      "hasBody": false
    }
  },
  "recipes": {
    "recipeBrandLaunch": {
      "operationId": "recipeBrandLaunch",
      "title": "Brand Launch Readiness",
      "description": "Pre-launch checklist for brand domains including DNS, SSL, email auth, and social availability. Saves 4 credits.",
      "method": "GET",
      "path": "/v1/recipes/brand-launch",
      "pathParams": [],
      "queryParams": [
        "domain",
        "brand_name",
        "platforms"
      ],
      "hasBody": false
    },
    "recipeCompetitorIntel": {
      "operationId": "recipeCompetitorIntel",
      "title": "Competitor Intelligence",
      "description": "Competitor domain infrastructure analysis including tech stack and DNS configuration. Saves 5 credits.",
      "method": "GET",
      "path": "/v1/recipes/competitor-intel",
      "pathParams": [],
      "queryParams": [
        "domain",
        "discover_subdomains",
        "analyze_infrastructure",
        "analyze_email"
      ],
      "hasBody": false
    },
    "recipeDefensiveRegistration": {
      "operationId": "recipeDefensiveRegistration",
      "title": "Defensive Registration",
      "description": "Brand protection through strategic domain acquisition recommendations. Saves 8 credits.",
      "method": "GET",
      "path": "/v1/recipes/defensive-registration",
      "pathParams": [],
      "queryParams": [
        "brand",
        "owned_domains",
        "priority_tlds",
        "include_typos",
        "budget"
      ],
      "hasBody": false
    },
    "recipeDnsMigration": {
      "operationId": "recipeDnsMigration",
      "title": "DNS Migration Check",
      "description": "Pre-migration checklist and current DNS configuration snapshot. Saves 5 credits.",
      "method": "GET",
      "path": "/v1/recipes/dns-migration",
      "pathParams": [],
      "queryParams": [
        "domain",
        "target_nameservers",
        "critical_records"
      ],
      "hasBody": false
    },
    "recipeDomainFinder": {
      "operationId": "recipeDomainFinder",
      "title": "Domain Finder",
      "description": "AI-powered domain discovery with filtering and availability checking. Saves 13 credits.",
      "method": "GET",
      "path": "/v1/recipes/domain-finder",
      "pathParams": [],
      "queryParams": [
        "keywords",
        "tlds",
        "style",
        "max_length",
        "language",
        "limit"
      ],
      "hasBody": false
    },
    "recipeDueDiligence": {
      "operationId": "recipeDueDiligence",
      "title": "Domain Due Diligence",
      "description": "Complete domain acquisition analysis with registration, valuation, health, and brand protection insights. Saves 6 credits vs individual calls.",
      "method": "GET",
      "path": "/v1/recipes/due-diligence",
      "pathParams": [],
      "queryParams": [
        "domain",
        "include_competitors"
      ],
      "hasBody": false
    },
    "recipeEmailDeliverability": {
      "operationId": "recipeEmailDeliverability",
      "title": "Email Deliverability Audit",
      "description": "Complete email authentication and deliverability analysis (SPF, DKIM, DMARC). Saves 5 credits.",
      "method": "GET",
      "path": "/v1/recipes/email-deliverability",
      "pathParams": [],
      "queryParams": [
        "domain",
        "dkim_selectors",
        "check_blacklists"
      ],
      "hasBody": false
    },
    "recipeInfrastructureDiscovery": {
      "operationId": "recipeInfrastructureDiscovery",
      "title": "Infrastructure Discovery",
      "description": "Complete infrastructure mapping and attack surface analysis. Saves 10 credits.",
      "method": "GET",
      "path": "/v1/recipes/infrastructure-discovery",
      "pathParams": [],
      "queryParams": [
        "domain",
        "depth",
        "include_historical"
      ],
      "hasBody": false
    },
    "recipePhishingInvestigation": {
      "operationId": "recipePhishingInvestigation",
      "title": "Phishing Investigation",
      "description": "Evidence collection and analysis for suspected phishing domains. Saves 10 credits.",
      "method": "GET",
      "path": "/v1/recipes/phishing-investigation",
      "pathParams": [],
      "queryParams": [
        "suspicious_domain",
        "legitimate_domain",
        "collect_evidence"
      ],
      "hasBody": false
    },
    "recipePortfolioAudit": {
      "operationId": "recipePortfolioAudit",
      "title": "Portfolio Audit",
      "description": "Audit entire domain portfolio for health, valuation, and optimization opportunities. Saves up to 275 credits.",
      "method": "GET",
      "path": "/v1/recipes/portfolio-audit",
      "pathParams": [],
      "queryParams": [
        "domains",
        "include_valuation",
        "include_health",
        "include_pricing",
        "alert_expiring_days"
      ],
      "hasBody": false
    },
    "recipePortfolioAuditPost": {
      "operationId": "recipePortfolioAuditPost",
      "title": "Portfolio Audit (POST)",
      "description": "Audit domain portfolio via POST for larger domain lists.",
      "method": "POST",
      "path": "/v1/recipes/portfolio-audit",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "recipeThreatAssessment": {
      "operationId": "recipeThreatAssessment",
      "title": "Threat Assessment",
      "description": "Comprehensive typosquatting and brand threat analysis for security teams. Saves 22 credits.",
      "method": "GET",
      "path": "/v1/recipes/threat-assessment",
      "pathParams": [],
      "queryParams": [
        "domain",
        "analyze_threats",
        "max_threats",
        "include_evidence"
      ],
      "hasBody": false
    }
  },
  "security": {
    "bulkEmailCheck": {
      "operationId": "bulkEmailCheck",
      "title": "Bulk Email Check",
      "description": "Check multiple email domains against blacklists at once.",
      "method": "POST",
      "path": "/v1/email/check/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "bulkGetCertificates": {
      "operationId": "bulkGetCertificates",
      "title": "Bulk SSL Certificate Search",
      "description": "Search Certificate Transparency data for up to 10 domains with bounded concurrency. Results preserve input order and include per-domain errors.",
      "method": "POST",
      "path": "/v1/certificates/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "bulkGetEmailAuth": {
      "operationId": "bulkGetEmailAuth",
      "title": "Bulk Email Authentication",
      "description": "Check SPF, DKIM, DMARC, MTA-STS, TLS-RPT, and recursive SPF behavior for up to 10 domains. Results preserve input order and include per-domain errors.",
      "method": "POST",
      "path": "/v1/email-auth/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "bulkGetSubdomains": {
      "operationId": "bulkGetSubdomains",
      "title": "Bulk Subdomain Discovery",
      "description": "Run the passive subdomain evidence pipeline for up to 10 domains with bounded concurrency. Results preserve input order and include per-domain errors.",
      "method": "POST",
      "path": "/v1/subdomains/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "checkEmailBlacklist": {
      "operationId": "checkEmailBlacklist",
      "title": "Email Blacklist Check",
      "description": "Check if an email domain is on disposable/temporary email blacklists.",
      "method": "GET",
      "path": "/v1/email/check",
      "pathParams": [],
      "queryParams": [
        "email",
        "checks"
      ],
      "hasBody": false
    },
    "getCertificates": {
      "operationId": "getCertificates",
      "title": "SSL Certificates",
      "description": "Query Certificate Transparency logs. Find all SSL certificates issued for a domain.",
      "method": "GET",
      "path": "/v1/certificates",
      "pathParams": [],
      "queryParams": [
        "domain",
        "include_subdomains",
        "include_expired",
        "limit",
        "cursor"
      ],
      "hasBody": false
    },
    "getDomainReputation": {
      "operationId": "getDomainReputation",
      "title": "Domain Reputation",
      "description": "Check domain reputation across DNS, TLS, blacklist, parking, web presence, and email signals with score confidence metadata.",
      "method": "GET",
      "path": "/v1/reputation",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getEmailAuth": {
      "operationId": "getEmailAuth",
      "title": "Email Authentication",
      "description": "Check DMARC, SPF, DKIM, MTA-STS, TLS-RPT, and recursive SPF behavior for email security auditing.",
      "method": "GET",
      "path": "/v1/email-auth",
      "pathParams": [],
      "queryParams": [
        "domain",
        "selectors"
      ],
      "hasBody": false
    },
    "getEmailCompliance": {
      "operationId": "getEmailCompliance",
      "title": "Email Compliance",
      "description": "Provider-oriented sender readiness report for Google/Gmail and Microsoft Outlook.com high-volume requirements, using SPF, DKIM, DMARC, MTA-STS, TLS-RPT, BIMI, DNSSEC, CAA, and mail security checks.",
      "method": "GET",
      "path": "/v1/email/compliance",
      "pathParams": [],
      "queryParams": [
        "domain",
        "selectors",
        "providers"
      ],
      "hasBody": false
    },
    "getSslAudit": {
      "operationId": "getSslAudit",
      "title": "SSL Audit",
      "description": "Run a comprehensive live SSL/TLS audit for a domain, aggregating certificate, chain, revocation, HSTS, HTTP version, and TLS posture details.",
      "method": "GET",
      "path": "/v1/ssl/audit",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getSslChain": {
      "operationId": "getSslChain",
      "title": "SSL Chain",
      "description": "Analyze the certificate chain including issuer, validity, and trust chain verification.",
      "method": "GET",
      "path": "/v1/ssl/chain",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getSslDeepScan": {
      "operationId": "getSslDeepScan",
      "title": "SSL Deep Scan",
      "description": "Run a premium cached deep SSL/TLS scan for a domain. Returns a fresh cached result immediately when available, or starts a long-running scan and returns a signed polling token.",
      "method": "GET",
      "path": "/v1/ssl/deep-scan",
      "pathParams": [],
      "queryParams": [
        "domain",
        "refresh",
        "profile"
      ],
      "hasBody": false
    },
    "getSslExpiring": {
      "operationId": "getSslExpiring",
      "title": "SSL Expiry Check",
      "description": "Check if an SSL certificate is expiring soon with configurable alert threshold.",
      "method": "GET",
      "path": "/v1/ssl/expiring",
      "pathParams": [],
      "queryParams": [
        "domain",
        "days",
        "threshold_days"
      ],
      "hasBody": false
    },
    "getSslGrade": {
      "operationId": "getSslGrade",
      "title": "SSL Grade",
      "description": "Analyze SSL/TLS configuration and get a letter grade (A+ to F) with detailed scoring plus HSTS preload audit metadata.",
      "method": "GET",
      "path": "/v1/ssl/grade",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getSubdomains": {
      "operationId": "getSubdomains",
      "title": "Subdomain Finder",
      "description": "Return best-effort hostname evidence from public certificate and passive discovery sources. Coverage is incomplete, and results include provenance with optional DNS verification.",
      "method": "GET",
      "path": "/v1/subdomains",
      "pathParams": [],
      "queryParams": [
        "domain",
        "sources",
        "verify",
        "include_wildcards",
        "limit",
        "prefer_cache"
      ],
      "hasBody": false
    },
    "getTyposquatting": {
      "operationId": "getTyposquatting",
      "title": "Typosquatting Detection",
      "description": "Detect typosquatting threats with analysis of common typos, homoglyphs, and brand impersonation risks.",
      "method": "GET",
      "path": "/v1/typos",
      "pathParams": [],
      "queryParams": [
        "domain",
        "check_registered",
        "limit",
        "include_tld_swap"
      ],
      "hasBody": false
    },
    "getVulnerabilities": {
      "operationId": "getVulnerabilities",
      "title": "Vulnerability Intelligence",
      "description": "Correlate exposed software versions with authoritative public advisories and exploitation-priority data, and report deterministic web security misconfigurations separately. Results preserve evidence and unknown coverage.",
      "method": "GET",
      "path": "/v1/vulnerabilities",
      "pathParams": [],
      "queryParams": [
        "url",
        "domain",
        "mode"
      ],
      "hasBody": false
    },
    "validatePhoneNumber": {
      "operationId": "validatePhoneNumber",
      "title": "Phone Number Validation",
      "description": "Validate, normalize, and enrich international phone numbers with maintained offline numbering-plan and public allocation data. Results include coverage, provenance, freshness, and limitations without paid or per-number third-party lookups, and never claim current carrier, reachability, subscriber identity, or individual-number assignment.",
      "method": "POST",
      "path": "/v1/phone/validate",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "validatePhoneNumbersBulk": {
      "operationId": "validatePhoneNumbersBulk",
      "title": "Bulk Phone Number Validation",
      "description": "Validate and enrich up to 100 phone numbers in one privacy-first request. Preserves input order and duplicates, supports shared or per-item parsing, dialing-country, and language context, and makes no paid or per-number third-party lookup.",
      "method": "POST",
      "path": "/v1/phone/validate/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "verifyEmail": {
      "operationId": "verifyEmail",
      "title": "Email Verification",
      "description": "Verify email deliverability with syntax validation, MX/null MX lookup, reserved/test-domain detection, provider typo suggestions, MX provider fingerprinting, SPF/DMARC/MTA-STS/TLS-RPT evidence, local-part/domain intelligence, toxic/do-not-mail signals, confidence scoring, and industry-style deliverability status. Mailbox-level SMTP probing is deprecated and is not charged or performed.",
      "method": "GET",
      "path": "/v1/email/verify",
      "pathParams": [],
      "queryParams": [
        "email",
        "full"
      ],
      "hasBody": false
    },
    "verifyEmailBulk": {
      "operationId": "verifyEmailBulk",
      "title": "Bulk Email Verification",
      "description": "Verify multiple email addresses at once. Max 100 emails per request.",
      "method": "POST",
      "path": "/v1/email/verify/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    }
  },
  "social": {
    "bulkCheckSocialHandles": {
      "operationId": "bulkCheckSocialHandles",
      "title": "Bulk Social Handle Check",
      "description": "Check up to 10 social handles or resource identifiers in one request at the normal 2-credit rate per valid item, with no bulk discount. Invalid items return per-item errors and are not billed.",
      "method": "POST",
      "path": "/v1/social/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "checkSocialHandles": {
      "operationId": "checkSocialHandles",
      "title": "Social Handle Checker",
      "description": "Check username availability across social, developer, creator, and community platforms. Optionally resolve repositories, subreddits, Discord invites, Substack profiles, and federated accounts.",
      "method": "GET",
      "path": "/v1/social",
      "pathParams": [],
      "queryParams": [
        "handle",
        "platforms",
        "resources"
      ],
      "hasBody": false
    },
    "getSocialInfo": {
      "operationId": "getSocialInfo",
      "title": "Social Handle Reference",
      "description": "Returns supported username platforms, resource types, parameters, and examples for the social intelligence endpoint.",
      "method": "GET",
      "path": "/v1/social/info",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    }
  },
  "user": {
    "getCreditBalance": {
      "operationId": "getCreditBalance",
      "title": "Get Credit Balance",
      "description": "Get the active customer account credit balance without exposing transaction history.",
      "method": "GET",
      "path": "/v1/credits",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    }
  }
} as const;

export type EndpointManifest = typeof endpointManifest;
