/**
 * Generated by scripts/generate-sdks.ts.
 * Do not edit this file manually.
 */

export const endpointManifest = {
  "availability": {
    "bulkCheckDomains": {
      "title": "Bulk Domain Check",
      "description": "Check availability of multiple complete domain names at once.",
      "method": "POST",
      "path": "/v1/status/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "checkDomainAvailability": {
      "title": "Domain Availability",
      "description": "Check if a domain name is available for registration across multiple TLDs. Uses RDAP for authoritative results.",
      "method": "GET",
      "path": "/v1/status",
      "pathParams": [],
      "queryParams": [
        "name",
        "tlds",
        "prefer_cache"
      ],
      "hasBody": false
    },
    "getCoverage": {
      "title": "RDAP Coverage",
      "description": "Get information about which TLDs are supported and their RDAP server status.",
      "method": "GET",
      "path": "/v1/coverage",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    }
  },
  "dns": {
    "buildDmarc": {
      "title": "DMARC Builder",
      "description": "Build a DMARC record with policy, reporting, and alignment options.",
      "method": "POST",
      "path": "/v1/tools/dmarc/build",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "buildSpf": {
      "title": "SPF Builder",
      "description": "Build an SPF record from configuration options with validation and recommendations.",
      "method": "POST",
      "path": "/v1/tools/spf/build",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "checkDkim": {
      "title": "DKIM Check",
      "description": "Check a specific DKIM selector for a domain and validate the public key.",
      "method": "GET",
      "path": "/v1/tools/dkim/check",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "discoverDkim": {
      "title": "DKIM Discovery",
      "description": "Discover DKIM selectors for a domain by checking common selector names.",
      "method": "GET",
      "path": "/v1/tools/dkim/discover",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "flattenSpf": {
      "title": "SPF Flattener",
      "description": "Flatten SPF record by resolving all includes into IP addresses to reduce DNS lookups.",
      "method": "POST",
      "path": "/v1/tools/spf/flatten",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "getAllDnsRecords": {
      "title": "DNS All Records",
      "description": "Get all DNS record types for a domain in a single call.",
      "method": "GET",
      "path": "/v1/dns/all",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDnsDiff": {
      "title": "DNS Diff",
      "description": "Compare DNS records between two dates to see what changed.",
      "method": "GET",
      "path": "/v1/dns/diff",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDnsHistory": {
      "title": "DNS History",
      "description": "Track DNS record changes over time. Data accumulates from API lookups.",
      "method": "GET",
      "path": "/v1/dns/history",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDnsPropagation": {
      "title": "DNS Propagation",
      "description": "Check DNS propagation across multiple global DNS servers.",
      "method": "GET",
      "path": "/v1/dns/propagation",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDnsRecords": {
      "title": "DNS Lookup",
      "description": "Query A, AAAA, MX, NS, TXT, CAA and other DNS records programmatically.",
      "method": "GET",
      "path": "/v1/dns",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDnsSecurity": {
      "title": "DNS Security",
      "description": "Analyze DNS security configuration including SPF, DKIM, DMARC, DNSSEC, and CAA records.",
      "method": "GET",
      "path": "/v1/dns/security",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDnsServers": {
      "title": "DNS Servers",
      "description": "Get list of global DNS servers used for propagation checks.",
      "method": "GET",
      "path": "/v1/dns/servers",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "validateDmarc": {
      "title": "DMARC Validator",
      "description": "Validate a DMARC record for syntax errors and configuration issues.",
      "method": "POST",
      "path": "/v1/tools/dmarc/validate",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "validateSpf": {
      "title": "SPF Validator",
      "description": "Validate an SPF record for syntax errors, DNS lookup limits, and best practices.",
      "method": "POST",
      "path": "/v1/tools/spf/validate",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    }
  },
  "domain": {
    "bulkDomainValue": {
      "title": "Bulk Domain Valuation",
      "description": "Get value estimates for multiple domains at once.",
      "method": "POST",
      "path": "/v1/value/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "compareDomains": {
      "title": "Domain Compare",
      "description": "Compare two domains side-by-side across multiple metrics and attributes.",
      "method": "GET",
      "path": "/v1/compare",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDomainHealth": {
      "title": "Domain Health",
      "description": "Comprehensive health checks: DNS, SSL, email deliverability, security headers, and more.",
      "method": "GET",
      "path": "/v1/health",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDomainOverview": {
      "title": "Domain Overview",
      "description": "Comprehensive domain intelligence in one call: DNS, WHOIS, health, and reputation data aggregated into a single response.",
      "method": "GET",
      "path": "/v1/overview",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDomainProfile": {
      "title": "Domain Profile",
      "description": "Get normalized RDAP registration data: registrar, dates, nameservers, DNSSEC status.",
      "method": "GET",
      "path": "/v1/profile",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDomainScore": {
      "title": "Domain Score",
      "description": "Calculate an overall domain quality score based on multiple factors.",
      "method": "GET",
      "path": "/v1/score",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDomainValue": {
      "title": "Domain Valuation",
      "description": "Algorithmic domain value estimates based on length, TLD tier, dictionary words, and brandability.",
      "method": "GET",
      "path": "/v1/value",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getQuickHealth": {
      "title": "Quick Health Check",
      "description": "Fast health check with essential metrics only.",
      "method": "GET",
      "path": "/v1/health/quick",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getTldDetail": {
      "title": "TLD Detail",
      "description": "Get detailed information about a specific TLD.",
      "method": "GET",
      "path": "/v1/tlds/:tld",
      "pathParams": [
        "tld"
      ],
      "queryParams": [],
      "hasBody": false
    },
    "getTlds": {
      "title": "TLD List",
      "description": "Get list of all supported TLDs with metadata.",
      "method": "GET",
      "path": "/v1/tlds",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "suggestDomains": {
      "title": "Domain Suggestions",
      "description": "AI-powered domain name generator. Get brandable, short, and keyword-rich suggestions based on your keywords.",
      "method": "GET",
      "path": "/v1/suggest",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    }
  },
  "intelligence": {
    "categorizeWebsite": {
      "title": "Website Categorization",
      "description": "Classify websites into 350+ IAB-inspired categories using multi-signal analysis: keywords, schema.org, Open Graph, TLD heuristics, URL patterns, and HTML structure.",
      "method": "GET",
      "path": "/v1/categorize",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "categorizeWebsiteBulk": {
      "title": "Bulk Website Categorization",
      "description": "Categorize up to 10 websites in parallel with caching.",
      "method": "POST",
      "path": "/v1/categorize/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "getCompany": {
      "title": "Company Lookup",
      "description": "Extract company information from a domain. Get name, industry, and contact details.",
      "method": "GET",
      "path": "/v1/company",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDomainSimilarity": {
      "title": "Domain Similarity",
      "description": "Compare domains for similarity. Detect typosquatting with multiple algorithms.",
      "method": "GET",
      "path": "/v1/similarity",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getHosting": {
      "title": "Hosting Detection",
      "description": "Detect hosting provider, CDN, WAF, DNS provider, and email infrastructure.",
      "method": "GET",
      "path": "/v1/hosting",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getParkingDetection": {
      "title": "Parking Detection",
      "description": "Detect if a domain is parked or listed for sale on aftermarket platforms. Identifies parking providers via DNS, HTTP redirect, and HTML content analysis.",
      "method": "GET",
      "path": "/v1/parking",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getRedirects": {
      "title": "Redirect Chain",
      "description": "Follow URL redirect chains. Detect HTTPS upgrades, domain changes, and landing pages.",
      "method": "GET",
      "path": "/v1/redirects",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getTechStack": {
      "title": "Tech Stack Detection",
      "description": "Detect website technologies: CDN, CMS, frameworks, analytics, and more.",
      "method": "GET",
      "path": "/v1/tech",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    }
  },
  "meta": {
    "getPricingInfo": {
      "title": "API Pricing Info",
      "description": "Get credit costs per endpoint and API pricing information.",
      "method": "GET",
      "path": "/v1/pricing",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    }
  },
  "osint": {
    "bulkWhois": {
      "title": "Bulk WHOIS Lookup",
      "description": "Get WHOIS data for multiple domains at once.",
      "method": "POST",
      "path": "/v1/whois/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "getDnsReverseNs": {
      "title": "Reverse NS Lookup",
      "description": "Find domains that use a specific nameserver.",
      "method": "GET",
      "path": "/v1/dns/reverse/ns",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDomainGraph": {
      "title": "Domain Graph",
      "description": "Map domain relationships through shared infrastructure and registrant data.",
      "method": "GET",
      "path": "/v1/graph",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDomainLifecycle": {
      "title": "Domain Lifecycle",
      "description": "Get domain lifecycle information including registration date, expiration date, age, and lifecycle phase. Returns Fastly-style status flags.",
      "method": "GET",
      "path": "/v1/lifecycle",
      "pathParams": [],
      "queryParams": [
        "domain"
      ],
      "hasBody": false
    },
    "getIpInfo": {
      "title": "IP Geolocation",
      "description": "Get IP addresses with geolocation, ASN, and hosting provider information.",
      "method": "GET",
      "path": "/v1/ip",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getMacInfo": {
      "title": "MAC Address Lookup",
      "description": "Lookup MAC address vendor information. Identify network device manufacturers.",
      "method": "GET",
      "path": "/v1/mac",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getReverseIp": {
      "title": "Reverse IP Lookup",
      "description": "Find all domains hosted on a specific IP address.",
      "method": "GET",
      "path": "/v1/reverse/ip",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getReverseMx": {
      "title": "Reverse MX Lookup",
      "description": "Find all domains using a specific mail server for email infrastructure mapping.",
      "method": "GET",
      "path": "/v1/reverse/mx",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getWhois": {
      "title": "WHOIS Lookup",
      "description": "Get structured WHOIS/RDAP registration data for a domain.",
      "method": "GET",
      "path": "/v1/whois",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getWhoisHistory": {
      "title": "WHOIS History",
      "description": "Track WHOIS record changes over time. Shows registrar transfers, expiry extensions, nameserver changes, and privacy toggles. Data accumulates from API lookups.",
      "method": "GET",
      "path": "/v1/whois/history",
      "pathParams": [],
      "queryParams": [
        "domain",
        "limit"
      ],
      "hasBody": false
    }
  },
  "pricing": {
    "bulkPricing": {
      "title": "Bulk Pricing",
      "description": "Get pricing for multiple domains at once.",
      "method": "POST",
      "path": "/v1/prices/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "comparePrices": {
      "title": "Compare Registrar Prices",
      "description": "Compare domain prices across multiple registrars.",
      "method": "GET",
      "path": "/v1/prices/compare",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getPrices": {
      "title": "Domain Pricing",
      "description": "Get domain registration and renewal prices across registrars.",
      "method": "GET",
      "path": "/v1/prices",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getRegistrars": {
      "title": "List Registrars",
      "description": "Get list of supported registrars with pricing data.",
      "method": "GET",
      "path": "/v1/prices/registrars",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getTldPricing": {
      "title": "TLD Pricing",
      "description": "Get pricing for a specific TLD across registrars.",
      "method": "GET",
      "path": "/v1/prices/tld/:tld",
      "pathParams": [
        "tld"
      ],
      "queryParams": [],
      "hasBody": false
    }
  },
  "recipes": {
    "recipeBrandLaunch": {
      "title": "Brand Launch Readiness",
      "description": "Pre-launch checklist for brand domains including DNS, SSL, email auth, and social availability. Saves 6 credits.",
      "method": "GET",
      "path": "/v1/recipes/brand-launch",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "recipeCompetitorIntel": {
      "title": "Competitor Intelligence",
      "description": "Competitor domain infrastructure analysis including tech stack and DNS configuration. Saves 8 credits.",
      "method": "GET",
      "path": "/v1/recipes/competitor-intel",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "recipeDefensiveRegistration": {
      "title": "Defensive Registration",
      "description": "Brand protection through strategic domain acquisition recommendations. Saves 10 credits.",
      "method": "GET",
      "path": "/v1/recipes/defensive-registration",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "recipeDnsMigration": {
      "title": "DNS Migration Check",
      "description": "Pre-migration checklist and current DNS configuration snapshot. Saves 6 credits.",
      "method": "GET",
      "path": "/v1/recipes/dns-migration",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "recipeDomainFinder": {
      "title": "Domain Finder",
      "description": "AI-powered domain discovery with filtering and availability checking. Saves 15 credits.",
      "method": "GET",
      "path": "/v1/recipes/domain-finder",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "recipeDueDiligence": {
      "title": "Domain Due Diligence",
      "description": "Complete domain acquisition analysis with registration, valuation, health, and brand protection insights. Saves 8 credits vs individual calls.",
      "method": "GET",
      "path": "/v1/recipes/due-diligence",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "recipeEmailDeliverability": {
      "title": "Email Deliverability Audit",
      "description": "Complete email authentication and deliverability analysis (SPF, DKIM, DMARC). Saves 7 credits.",
      "method": "GET",
      "path": "/v1/recipes/email-deliverability",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "recipeInfrastructureDiscovery": {
      "title": "Infrastructure Discovery",
      "description": "Complete infrastructure mapping and attack surface analysis. Saves 13 credits.",
      "method": "GET",
      "path": "/v1/recipes/infrastructure-discovery",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "recipePhishingInvestigation": {
      "title": "Phishing Investigation",
      "description": "Evidence collection and analysis for suspected phishing domains. Saves 12 credits.",
      "method": "GET",
      "path": "/v1/recipes/phishing-investigation",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "recipePortfolioAudit": {
      "title": "Portfolio Audit",
      "description": "Audit entire domain portfolio for health, valuation, and optimization opportunities. Saves up to 280 credits.",
      "method": "GET",
      "path": "/v1/recipes/portfolio-audit",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "recipePortfolioAuditPost": {
      "title": "Portfolio Audit (POST)",
      "description": "Audit domain portfolio via POST for larger domain lists.",
      "method": "POST",
      "path": "/v1/recipes/portfolio-audit",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "recipeThreatAssessment": {
      "title": "Threat Assessment",
      "description": "Comprehensive typosquatting and brand threat analysis for security teams. Saves 25 credits.",
      "method": "GET",
      "path": "/v1/recipes/threat-assessment",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    }
  },
  "security": {
    "bulkEmailCheck": {
      "title": "Bulk Email Check",
      "description": "Check multiple email domains against blacklists at once.",
      "method": "POST",
      "path": "/v1/email/check/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    },
    "checkEmailBlacklist": {
      "title": "Email Blacklist Check",
      "description": "Check if an email domain is on disposable/temporary email blacklists.",
      "method": "GET",
      "path": "/v1/email/check",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "downloadEmailBlacklist": {
      "title": "Download Email Blacklist",
      "description": "Download the full email blacklist database in various formats.",
      "method": "GET",
      "path": "/v1/email/blacklist/download",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getCertificates": {
      "title": "SSL Certificates",
      "description": "Query Certificate Transparency logs. Find all SSL certificates issued for a domain.",
      "method": "GET",
      "path": "/v1/certificates",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getDomainReputation": {
      "title": "Domain Reputation",
      "description": "Check domain reputation across security feeds, blacklists, and threat intelligence.",
      "method": "GET",
      "path": "/v1/reputation",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getEmailAuth": {
      "title": "Email Authentication",
      "description": "Check DMARC, SPF, and DKIM configurations for email security auditing.",
      "method": "GET",
      "path": "/v1/email-auth",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getEmailBlacklistInfo": {
      "title": "Email Blacklist Info",
      "description": "Get information about the email blacklist database.",
      "method": "GET",
      "path": "/v1/email/blacklist",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getSslChain": {
      "title": "SSL Chain",
      "description": "Analyze the certificate chain including issuer, validity, and trust chain verification.",
      "method": "GET",
      "path": "/v1/ssl/chain",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getSslExpiring": {
      "title": "SSL Expiry Check",
      "description": "Check if an SSL certificate is expiring soon with configurable alert threshold.",
      "method": "GET",
      "path": "/v1/ssl/expiring",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getSslGrade": {
      "title": "SSL Grade",
      "description": "Analyze SSL/TLS configuration and get a letter grade (A+ to F) with detailed scoring.",
      "method": "GET",
      "path": "/v1/ssl/grade",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getSubdomains": {
      "title": "Subdomain Finder",
      "description": "Discover subdomains using Certificate Transparency and DNS enumeration.",
      "method": "GET",
      "path": "/v1/subdomains",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "getTyposquatting": {
      "title": "Typosquatting Detection",
      "description": "Detect typosquatting threats with analysis of common typos, homoglyphs, and brand impersonation risks.",
      "method": "GET",
      "path": "/v1/typos",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    },
    "verifyEmail": {
      "title": "Email Verification",
      "description": "Verify email deliverability with syntax validation, MX lookup, disposable detection, and optional SMTP mailbox verification. Basic check costs 1 credit; full SMTP check costs 5 credits.",
      "method": "GET",
      "path": "/v1/email/verify",
      "pathParams": [],
      "queryParams": [
        "email",
        "full"
      ],
      "hasBody": false
    },
    "verifyEmailBulk": {
      "title": "Bulk Email Verification",
      "description": "Verify multiple email addresses at once. Max 100 emails per request.",
      "method": "POST",
      "path": "/v1/email/verify/bulk",
      "pathParams": [],
      "queryParams": [],
      "hasBody": true
    }
  },
  "social": {
    "checkSocialHandles": {
      "title": "Social Handle Checker",
      "description": "Check username availability across social platforms like GitHub, Reddit, and more.",
      "method": "GET",
      "path": "/v1/social",
      "pathParams": [],
      "queryParams": [],
      "hasBody": false
    }
  }
} as const;

export type EndpointManifest = typeof endpointManifest;
